### ISSUE TITLE
Missing .gitignore

### ISSUE THREAD

**Issue by flacial** [emanation-ai/luminosity#1]
### Expected behavior

To have a [`.gitignore`](https://github.com/github/gitignore/blob/main/Node.gitignore) and not include `node_modules`. 

### Actual behavior

Pushing to the repo includes [`node_modules`](https://github.com/emanation-ai/luminosity/tree/main/node_modules)

**Comment by AlbertoV5** [comment]
Just seeing this. Added `.gitignore`.
